jQuery(function($){if('undefined'==typeof(iworks_upprev)){return;}
var iuvw=false;var iuvu=true;var iuvr_track_view=true;var iuvr=typeof(_gaq)!='undefined';var iuvr_opt_noninteraction=iworks_upprev.ga_opt_noninteraction==1;var iuve=1000;var iuq=600;function iuva(){var iuvo=false;if(iworks_upprev.offset_element&&$(iworks_upprev.offset_element)){if($(iworks_upprev.offset_element).length>0){iuvo=iufe($('html'))+$(window).height()>$(iworks_upprev.offset_element).offset().top;}else{iuvo=iufe($('html'))+$(window).height()>=$(document).height()*iworks_upprev.offset_percent/100;}}else{iuvo=(iufe($('html'))+$(window).height()>=$(document).height()*iworks_upprev.offset_percent/100);}
box=$('#upprev_box');if(iuvo&&!iuvw){if('fade'==iworks_upprev.animation){box.fadeIn(iuve);}else{box.css({display:'block'});iuvi=iworks_upprev.css_side+'px';iuvs=iworks_upprev.css_bottom+'px';switch(iworks_upprev.position.all){case'bottom':case'top':box.css('left',(($(window).width()-box.width()-parseInt(box.css('padding-left').replace(/px$/,''))-parseInt(box.css('padding-right').replace(/px$/,'')))/2)+'px')
break;case'left-middle':case'right-middle':box.css('top',(($(window).height()-box.height()-parseInt(box.css('padding-top').replace(/px$/,''))-parseInt(box.css('padding-bottom').replace(/px$/,'')))/2)+'px')
break;}
box.stop().animate(iufr(iuvi,iuvs),iuq);}
iuvu=false;if(iuvr&&iuvr_track_view&&iworks_upprev.ga_track_views==1){_gaq.push(['_trackEvent','upPrev',iworks_upprev.title,null,0,iuvr_opt_noninteraction]);iuvr_track_view=false;}}
else if(iuvw&&iufe($('html'))==0){iuvw=false;}
else if(!iuvu){iuvu=true;if(iworks_upprev.animation=='fade'){box.fadeOut(iuve);}else{iuvi=iufq(box);iuvs=iufw(box);box.stop().animate(iufr(iuvi,iuvs),iuq);}}}
$(document).ready(function(){$.get(iworks_upprev.url,function(data){$('body').append(data);$(window).bind('scroll',function(){iuva();});$('#upprev_rise').click(function(){$(this).fadeOut(iuve,function(){iuva();$(window).bind('scroll',function(){iuva();});});});$("#upprev_close").click(function(){$('#upprev_box').fadeOut("slow",function(){$(window).unbind('scroll');$('#upprev_rise').css({bottom:0,right:0}).fadeIn(iuve);});return false;});if(iworks_upprev.url_new_window==1||iworks_upprev.ga_track_clicks==1){$('#upprev_box a[id!=upprev_close]').click(function(){$(this).attr('style','bacground-color:lime');if(iworks_upprev.url_new_window==1){window.open($(this).attr('href'));}
if(iuvr&&iworks_upprev.ga_track_clicks==1){_gaq.push(['_trackEvent','upPrev',iworks_upprev.title,$(this).html(),1,iuvr_opt_noninteraction]);}
if(iworks_upprev.url_new_window==1){return false;}});}
box=$('#upprev_box');box.css({width:iworks_upprev.css_width});if(iworks_upprev.animation=='flyout'){iuvi=iufq(box);iuvs=iufw(box);}else if('fade'==iworks_upprev.animation){iuvs=iworks_upprev.css_side;iuvi=iworks_upprev.css_bottom;box.css({display:'none'});}
box.css(iufr(iuvi,iuvs));iuva();});});function iufq(box){return'-'+(box.width()+parseInt(box.css('padding-top').replace(/px$/,''))+parseInt(box.css('padding-bottom').replace(/px$/,'')))+'px';}
function iufw(box){return'-'+(box.width()+parseInt(box.css('padding-left').replace(/px$/,''))+parseInt(box.css('padding-right').replace(/px$/,'')))+'px';}
function iufe(h){return parseInt(h.css('margin-top').replace(/px$/,''))-h.offset().top;}
function iufr(iuvs,iuvi){iuvp={};switch(iworks_upprev.position.all){case'left':iuvp.left=iuvi;iuvp.bottom=iuvs;break;case'bottom':iuvp.bottom=iuvs;break;case'top':iuvp.top=iuvs;break;case'left-top':iuvp.left=iuvi;iuvp.top=iuvs;break;case'left-middle':iuvp.left=iuvi;break;case'right':iuvp.right=iuvi;iuvp.bottom=iuvs;break;case'right-middle':iuvp.right=iuvi;break;case'right-top':iuvp.right=iuvi;iuvp.top=iuvs;break;default:alert(iworks_upprev.position);break;}
return iuvp;}});